### ISSUE TITLE
Диаграммы UML: диаграммы деятельности

### ISSUE THREAD

**Issue by AvatarMod** [AVAtarMod/Linux_Ecosystem#1]
- [ ] Изменить термин "ретрансляция", "видеопоток" на трансляцию данных с сервера на клиент и с клиента на сервер. 
- [ ] Обозначить различия между трансляцией данных клиента на сервер и с сервера на клиент (т.е есть данные **для** устройств вывода и данные **от** устройств ввода)
- [x] Спросить о том, правильно располагать элементы между секциями
- [ ] Добавить завершение трансляции в диаграммах

**Comment by AvatarMod** [comment]
Ссылки на материал по диаграммам деятельности UML 2.0:

- https://swi.cs.vsb.cz/RUPSmall/core.base_rup/guidances/supportingmaterials/differences_between_uml_1_x_and_uml_2_0_CA70F2E6.html (описаны хорошие примеры, символы, нюансы применения)
- https://www.lucidchart.com/pages/uml-activity-diagram#section_3 (описывает доступные символы)

**Comment by AVAtarMod** [comment]
- [ ] Изменить термин "ретрансляция", "видеопоток" на трансляцию данных с сервера на клиент и с клиента на сервер. 
- [ ] Обозначить различия между трансляцией данных клиента на сервер и с сервера на клиент (т.е есть данные **для** устройств вывода и данные **от** устройств ввода)

**Comment by AvatarMod** [comment]
Информация от @Yura-Zh43: https://github.com/AVAtarMod/Linux_Ecosystem/commit/6f515e26fcab5a38dd8b6368335db9d679bc9784#commitcomment-84799267

**Comment by AVAtarMod** [comment]
- [ ] Спросить о том, правильно располагать элементы между секциями
